###
# Configuration file
# Contains site data, core jekyll config, plugin config, etc.

## Org settings
title: Site title
logo: /assets/images/global/logo.svg
email: email
phone: phone
city: city
state: state
zip: zip

## Site Description
# used in meta tags
description: >
  I see pride. I see power. I see a badass starter that don't take no crap off of nobody!

## Core Site Settings
# jekyll configuration 
baseurl: ''
url: 'http://carsonjon.es'
permalink: none
assets-base-url: '/assets/'
source: src
destination: dist
site-theme: default
compress_html:
  clippings: all
  comments: all
  ignore:
    envs: ['dev']
# modules
include: ['_pages', '_posts', '_data']
exclude: ['assets', 'js', 'sass', 'node_modules', Gemfile, Gemfile.lock, notes.txt, package.json, README.md, 'bower.json']
keep_files:
  - assets
markdown: kramdown
gems:
  - jekyll-seo-tag

# SEO Specific Settings
twitter:
  username: carsonjonze
  domain: carsonjon.es
facebook:
  app_id: 
social:
  name: Carson Jones
  links: 
    - http://carsonjon.es
